services:

  php:
    build:
      context: docker
      dockerfile: php.docker
    user: 1000:1000
    volumes:
      - .:/app
      - composer:/composer
    depends_on:
      - db

  nginx:
    image: nginx:1.19-alpine
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - php
    working_dir: /app

  db:
      image: postgres:15-alpine
      volumes:
          - db:/var/lib/postgresql/data
      environment:
          POSTGRES_PASSWORD: $DB_PASSWORD
          POSTGRES_USER: $DB_USERNAME
          POSTGRES_DB: $DB_DATABASE
      ports:
          - 54321:5432

volumes:
  db:
  composer:
